### ISSUE TITLE
F-Droid reproducible build failed

### ISSUE THREAD

**Issue by linsui** [brandonp2412/FitBook#26]
1.0.77 
[com.presley.fit_book_821.apk.html.zip](https://github.com/user-attachments/files/16373526/com.presley.fit_book_821.apk.html.zip)

**Comment by brandonp2412** [comment]
Sorry mate I probably edited the code while my deploy script was running, next one will be all good

**Comment by linsui** [comment]
https://gitlab.com/linsui/fdroiddata/-/jobs/7435504548 Looks like the flutter version is different.

**Comment by brandonp2412** [comment]
@linsui I think it's because I packed the [MyFoodData](https://tools.myfooddata.com/nutrition-facts-database-spreadsheet.php) into a zip file https://gitlab.com/brandonp2412/fit-book/-/jobs/7588801969#L1414

Is there any chance I can keep this in or do I have to go back to including this big arsed CSV in my app build?

**Comment by linsui** [comment]
You can add that path to scanignore.

**Comment by linsui** [comment]
This is fixed, thanks!
